[project]
<<<<<<< HEAD
name = "learning-ci-pipeline"
version = "0.1.0"
description = ""
authors = [
    {name = "Dutta21341",email = "duttasanskar@gmail.com"}
=======
name = "learning_ci_pipeline"
version = "0.1.0"
description = ""
authors = [
    {name = "Sanskar_Dutta"}
>>>>>>> 3e02ad6 (Initial CI pipeline setup)
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

<<<<<<< HEAD
[tool.poetry]
packages = [{include = "learning_ci_pipeline", from = "src"}]

=======

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
>>>>>>> 3e02ad6 (Initial CI pipeline setup)

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.4"
ruff = "^0.9.6"

<<<<<<< HEAD
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
=======
>>>>>>> 3e02ad6 (Initial CI pipeline setup)
