name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install --no-root
      - name: Run Linting
        run: poetry run ruff check . && poetry run pylint --recursive=y .

  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        run: docker --version
      - name: Build Docker image
        run: |
          docker build -t my-app .
          docker run my-app
      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-app sanskar152/my-app:latest
          docker push sanskar152/my-app:latest
