name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install --no-root
      - name: Run Linting
        run: poetry run ruff check . && poetry run pylint --recursive=y .

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        run: |
          docker --version
      - name: Build Docker image
        run: |
          docker build -t my-app .
          docker run my-app
      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag my-app sanskar152/my-app:latest
          docker push sanskar152/my-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
